project_id = "egdelmcijszuapcpglsy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true, quality = 80 }

[auth]
enabled = true
port = 54331
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.jwt]
secret = "super-secret-jwt-token-with-at-least-32-characters-long"
aud = "backoffice"
issuer = "https://keycloak.ialla.fr/realms/haas"

[auth.external.keycloak]
enabled = true
client_id = "backoffice"
issuer = "https://keycloak.ialla.fr/realms/haas"
jwks_uri = "https://keycloak.ialla.fr/realms/haas/protocol/openid-connect/certs"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
test_otp = "123456"

[edge-functions]
enabled = true
port = 54330

[functions.ai-graph-generator]
verify_jwt = true

[functions.auth-admin]
verify_jwt = false

[functions.planka-integration]
verify_jwt = true

[functions.candidate-auth]
verify_jwt = false

[functions.keycloak-user-management]
verify_jwt = false

[functions.resource-booking]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false