project_id = "egdelmcijszuapcpglsy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv6"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://127.0.0.1:8080", "http://localhost:8080"]
jwt_expiry = 3600
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.external.keycloak]
enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[functions.ai-graph-generator]
verify_jwt = true

[functions.auth-admin]
verify_jwt = false

[functions.planka-integration]
verify_jwt = false

[functions.candidate-auth]
verify_jwt = false

[functions.keycloak-user-management]
verify_jwt = false

[functions.resource-booking]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.nextcloud-integration]
verify_jwt = false

[functions.nc-orchestrator]
verify_jwt = false

[functions.project-details]
verify_jwt = false

[functions.sync-profile]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-register]
verify_jwt = false

[functions.auth-check]
verify_jwt = false

[functions.project-kickoff]
verify_jwt = false

[functions.project-orchestrator]
verify_jwt = false

[functions.send-event-invitations]
verify_jwt = false